repositories:
- name: bitwarden
  url: https://charts.bitwarden.com/
- name: longhorn
  url: https://charts.longhorn.io

releases:
- name: bitwarden
  namespace: security
  chart: bitwarden/sm-operator
- name: pihole
  namespace: security
  chart: ../pihole
  values:
  - ./values/pihole.yaml
  secrets:
  - ./values/pihole-secret.yaml
- name: longhorn
  namespace: storage
  chart: longhorn/longhorn