apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: "linuxserver/qbittorrent:latest"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: p2p
            containerPort: 6881
            protocol: TCP
          - name: p2pudp
            containerPort: 6881
            protocol: UDP
        imagePullPolicy: IfNotPresent
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "UTC"
          - name: WEBUI_PORT
            value: "8080"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: data
            mountPath: /data
            subPath: qbittorrent
      initContainers:
      - name: create-directories
        image: "busybox:latest"
        command: ["sh", "-c", "mkdir /data/downloads && chown -R 1000:1000 /config /data/downloads"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: data
            mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: media-pvc